### ISSUE TITLE
UI not loading

### ISSUE THREAD

**Issue by HyperSmartian** [nukeop/nuclear#1471]
**Windows**

**0.6.22**

**The application window opens and gets stuck as a grey screen, i'm learning to program and just a FOSS enthusiast so no clue what's wrong.**

**Comment by Narga** [comment]
I Confirmed.
MacOS Monterey, M1

**Comment by nukeop** [comment]
I fixed it in 0.6.23. Thanks for reporting. I deleted the broken release too.

**Comment by Narga** [comment]
<img width="1440" alt="Screen Shot 2023-06-23 at 09 17 59" src="https://github.com/nukeop/nuclear/assets/212624/c6a1b3ac-827f-49f0-b4bc-05e3f3b5adae">
Still happened with 0.6.23. I removed the old version with ccleaner, reinstalled but still get blank window

**Comment by nukeop** [comment]
I deleted 0.6.23 as well, please use 0.6.21 until I fix this.

**Comment by maboroshin** [comment]
We can download v0.6.23 again. But it is the same as the image above. Gray screen for Windows.
