### ISSUE TITLE
Unable to add long Youtube playlist | youtube fetch playlist error  TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by Ascend910** [nukeop/nuclear#1724]
**Platform:**
Ubuntu 20.04

**Nuclear version:**
0.6.39

**Description of the issue:**
When searching for YouTube playlist, the playlist will not show up. Chrome Debugger shows the following error:
```
youtube fetch playlist error  
TypeError: Cannot read property '0' of undefined
```

Full error:
https://pastebin.com/0WAWjQ7g

Screenshot:
![image](https://github.com/user-attachments/assets/08a6ffba-bcf5-4d05-a6c8-a7e69ca1dbe3)

**Comment by nukeop** [comment]
Can you give us a link to the playlist you were trying to import?

**Comment by Ascend910** [comment]
If I remember it right, any playlist linger then 512 songs will fail to import, here is the one I am trying to import which is 1016 songs    
https://www.youtube.com/playlist?list=PLEUdk8hER43Uc7d2TWCW0HgQj8MEnC3Yq

**Comment by rishiral** [comment]
Hi, can I work on this issue? Unless it is an issue with the YouTube API itself.

**Comment by rishiral** [comment]
Hi, can I work on this issue? Unless it is an issue with the YouTube API itself.

**Comment by nukeop** [comment]
This should be closed now, I updated the youtube scraper.

**Comment by nukeop** [comment]
Oops, I was mistaken. You can look into it.

**Comment by ImGGAAVVIINN** [comment]
Hey, I opened this issue on the account I use for school. The issue is still happening on the latest version, I have tested with a shorter playlist and it will work. But longer playlist still give the error

**Comment by nukeop** [comment]
Yeah I didn't do anything to fix this yet.

**Comment by nukeop** [comment]
I fixed that now. Just tested it and could download that playlist with 1134 tracks.

**Comment by ImGGAAVVIINN** [comment]
I tried to compile the latest commit, it doesn't seem to fix the issue. Ubuntu btw

**Comment by nukeop** [comment]
What do you mean 'it doesn't seem to fix the issue'?

**Comment by ImGGAAVVIINN** [comment]
The same things still happening with long playlist not showing up.
Or maybe I am doing something wrong idk, I'll just wait for the next release, I guess
