### ISSUE TITLE
Docs files ending in "ptbr" keep showing as "modified"

### ISSUE THREAD

**Issue by Venryx** [nukeop/nuclear#534]
Git keeps thinking the doc files ending in "ptbr" (electron-ptbr.md, README-ptbr.md) are locally modified. I hit "Revert", and it says it succeeded, but I get the same error messages when trying to rebase, merge, and such.

```
git.exe stash
git.exe checkout -f c534aa101391256e51b3b0bb0ad96faec9ac522a --
Start Rebase

Pick 1: 0520f5af196d1a6f701eb3d73920610f119cb493
* Fixed that an error when fingerprinting a track (calling fetchAcousticId), would cause the entire library scan operation to fail.
error: Your local changes to the following files would be overwritten by merge:
	docs/README-ptbr.md
	docs/electron-ptbr.md
Please commit your changes or stash them before you merge.
Aborting
fatal: cherry-pick failed

An unrecoverable error occurred.
```

I've tried stashing "my changes" as well, but immediately after doing so, it again says I need to stash my changes.

Thus, it makes me think something is wrong with Git, where it is unable to either retrieve the contents exactly as in the remote Git, or it's unable to correctly compare the two.

I have the latest version of Git for Windows (git version 2.23.0.windows.1), and the latest version of TortoiseGit as well (though this shouldn't matter since the issue is within Git itself).

I suspected it might have to do with the `autoCrlf` setting in Git, but I have it set to "input", so that shouldn't be causing a "locally modified" issue (it preserves the remote line-endings). (Also, I've used "TortoiseGit Diff" on the "local changes", and it shows absolutely no changes, even when enabling whitespace comparison.)

**Comment by Venryx** [comment]
This workaround appears to have worked: https://stackoverflow.com/questions/6335521/git-how-to-revert-2-files-that-are-stubbornly-stuck-at-changed-but-not-committ#comment37756033_14129301

However, it's still somewhat of a problem for developers to be unable to merge, rebase, etc. without applying a special command for two of the files -- well if this problem applies to more than just me anyway.

Since I don't see anyone else mentioning this, I'm guessing it's specific to my computer or config somehow. Thus, I'll close this issue for now.

If someone else hits in the future, let me know please so we can attempt to produce an in-repo fix.

**Comment by nukeop** [comment]
In `.gitattributes`, it is enforced that all files have LF line endings. Somebody committed these files with windows line endings though. I corrected the problem and pushed to master.

**Comment by Venryx** [comment]
The issue came back, but I resolved it by completely deleting the ".git" folder and re-cloning. (just leaving here in case someone else hits the issue)
